# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 768)
        MainWindow.setMinimumSize(QtCore.QSize(1366, 768))
        MainWindow.setWindowFlag(QtCore.Qt.FramelessWindowHint)
        MainWindow.setToolTipDuration(-1)
        MainWindow.setStyleSheet("QMainWindow {background: transparent; }\n"
"QToolTip {\n"
"    color: #ffffff;\n"
"    background-color: rgba(27, 29, 35, 160);\n"
"    border: 1px solid rgb(40, 40, 40);\n"
"    border-radius: 2px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1366, 768))
        self.centralwidget.setToolTipDuration(-1)
        self.centralwidget.setStyleSheet("background: transparent;\n"
"color: rgb(210, 210, 210);")
        self.centralwidget.setObjectName("centralwidget")
        self.frame_main = QtWidgets.QFrame(self.centralwidget)
        self.frame_main.setGeometry(QtCore.QRect(0, 0, 1366, 768))
        self.frame_main.setMinimumSize(QtCore.QSize(1366, 768))
        self.frame_main.setStyleSheet("/* LINE EDIT */\n"
"QLineEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding-left: 10px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}\n"
"\n"
"/* SCROLL BARS */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    height: 14px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(85, 170, 255);\n"
"    min-width: 25px;\n"
"    border-radius: 7px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-right-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-left-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 14px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
" QScrollBar::handle:vertical {    \n"
"    background: rgb(85, 170, 255);\n"
"    min-height: 25px;\n"
"    border-radius: 7px\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
"/* CHECKBOX */\n"
"QCheckBox::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background: 3px solid rgb(52, 59, 72);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"    background-image: url(:/16x16/data/resources/icons/16x16/cil-check-alt.png);\n"
"}\n"
"\n"
"/* RADIO BUTTON */\n"
"QRadioButton::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QRadioButton::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background: 3px solid rgb(94, 106, 130);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"}\n"
"\n"
"/* COMBOBOX */\n"
"QComboBox{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 25px; \n"
"    border-left-width: 3px;\n"
"    border-left-color: rgba(39, 44, 54, 150);\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;    \n"
"    background-image: url(:/16x16/data/resources/icons/16x16/cil-arrow-bottom.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
" }\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}\n"
"\n"
"/* SLIDERS */\n"
"QSlider::groove:horizontal {\n"
"    border-radius: 9px;\n"
"    height: 18px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:horizontal:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background-color: rgb(85, 170, 255);\n"
"    border: none;\n"
"    height: 18px;\n"
"    width: 18px;\n"
"    margin: 0px;\n"
"    border-radius: 9px;\n"
"}\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: rgb(105, 180, 255);\n"
"}\n"
"QSlider::handle:horizontal:pressed {\n"
"    background-color: rgb(65, 130, 195);\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"    border-radius: 9px;\n"
"    width: 18px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:vertical:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background-color: rgb(85, 170, 255);\n"
"    border: none;\n"
"    height: 18px;\n"
"    width: 18px;\n"
"    margin: 0px;\n"
"    border-radius: 9px;\n"
"}\n"
"QSlider::handle:vertical:hover {\n"
"    background-color: rgb(105, 180, 255);\n"
"}\n"
"QSlider::handle:vertical:pressed {\n"
"    background-color: rgb(65, 130, 195);\n"
"}\n"
"\n"
"/* DateTimeEdit */\n"
"QDateTimeEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QDateTimeEdit :hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QDateTimeEdit::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 25px; \n"
"    border-left-width: 3px;\n"
"    border-left-color: rgba(39, 44, 54, 150);\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;    \n"
"    background-image: url(:/16x16/data/resources/icons/16x16/cil-arrow-bottom.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
" }\n"
"QDateTimeEdit QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}\n"
"\n"
"/* DoubleSpinBox */\n"
"QDoubleSpinBox {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QDoubleSpinBox :hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QDoubleSpinBox::up-arrow {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 25px; \n"
"    border-left-width: 3px;\n"
"    border-left-color: rgba(39, 44, 54, 150);\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;    \n"
"    background-image: url(:/16x16/data/resources/icons/16x16/cil-arrow-top.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
" }\n"
"QDoubleSpinBox::down-arrow {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 25px; \n"
"    border-left-width: 3px;\n"
"    border-left-color: rgba(39, 44, 54, 150);\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;    \n"
"    background-image: url(:/16x16/data/resources/icons/16x16/cil-arrow-bottom.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
" }\n"
"QDoubleSpinBox::up-button {\n"
"    background-color: transparent;\n"
" }\n"
"QDoubleSpinBox::down-button {\n"
"    background-color: transparent;\n"
" }\n"
"QDoubleSpinBox QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}\n"
"\n"
"/* Calendar Widget */\n"
"QCalendarWidget QToolButton {\n"
"    height: 40px;\n"
"    width: 120px;\n"
"    color: rgb(180,180,180);\n"
"    font-size: 16px;\n"
"    font: \"Segoe UI\";\n"
"    icon-size:20px, 20px;\n"
"    background-color:black;\n"
"}\n"
"\n"
"  /* header row */\n"
"QCalendarWidget  QWidget\n"
"{\n"
"    alternate-background-color: rgb(52, 59, 72);\n"
"}\n"
"  /*normal days */\n"
"QCalendarWidget QAbstractItemView:enabled {\n"
"    font-size:12px;\n"
"    font: \"Segoe UI\";\n"
"    color: rgb(180,180,180);\n"
"    background-color: black;\n"
"    selection-background-color: rgb(52, 59, 72); \n"
"    selection-color:rgb(85, 170, 255);\n"
"}\n"
"#qt_calendar_prevmonth{\n"
"    qproperty-icon: url(:/16x16/data/resources/icons/16x16/cil-arrow-left.png);\n"
"}\n"
"#qt_calendar_nextmonth{\n"
"    qproperty-icon: url(:/16x16/data/resources/icons/16x16/cil-arrow-right.png);\n"
"}")
        self.frame_main.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_main)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_header = QtWidgets.QFrame(self.frame_main)
        self.frame_header.setMinimumSize(QtCore.QSize(0, 42))
        self.frame_header.setMaximumSize(QtCore.QSize(16777215, 42))
        self.frame_header.setStyleSheet("background-color: rgb(27, 29, 35);")
        self.frame_header.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_header.setObjectName("frame_header")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_header)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_title = QtWidgets.QFrame(self.frame_header)
        self.frame_title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setLineWidth(0)
        self.frame_title.setObjectName("frame_title")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_title)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_icon = QtWidgets.QFrame(self.frame_title)
        self.frame_icon.setMinimumSize(QtCore.QSize(42, 42))
        self.frame_icon.setMaximumSize(QtCore.QSize(42, 42))
        self.frame_icon.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_icon.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_icon.setLineWidth(0)
        self.frame_icon.setObjectName("frame_icon")
        self.horizontalLayout_3.addWidget(self.frame_icon)
        self.label_title = QtWidgets.QLabel(self.frame_title)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_title.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("background: transparent;")
        self.label_title.setObjectName("label_title")
        self.horizontalLayout_3.addWidget(self.label_title)
        self.horizontalLayout_2.addWidget(self.frame_title)
        self.frame_system_buttons = QtWidgets.QFrame(self.frame_header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_system_buttons.sizePolicy().hasHeightForWidth())
        self.frame_system_buttons.setSizePolicy(sizePolicy)
        self.frame_system_buttons.setMaximumSize(QtCore.QSize(80, 16777215))
        self.frame_system_buttons.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_system_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_system_buttons.setObjectName("frame_system_buttons")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_system_buttons)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.button_minimize = QtWidgets.QPushButton(self.frame_system_buttons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_minimize.sizePolicy().hasHeightForWidth())
        self.button_minimize.setSizePolicy(sizePolicy)
        self.button_minimize.setMinimumSize(QtCore.QSize(40, 0))
        self.button_minimize.setMaximumSize(QtCore.QSize(40, 16777215))
        self.button_minimize.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.button_minimize.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/16x16/data/resources/icons/16x16/cil-window-minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_minimize.setIcon(icon)
        self.button_minimize.setObjectName("button_minimize")
        self.horizontalLayout_5.addWidget(self.button_minimize)
        self.button_close = QtWidgets.QPushButton(self.frame_system_buttons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_close.sizePolicy().hasHeightForWidth())
        self.button_close.setSizePolicy(sizePolicy)
        self.button_close.setMinimumSize(QtCore.QSize(40, 0))
        self.button_close.setMaximumSize(QtCore.QSize(40, 16777215))
        self.button_close.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.button_close.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/20x20/data/resources/icons/20x20/cil-x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_close.setIcon(icon1)
        self.button_close.setObjectName("button_close")
        self.horizontalLayout_5.addWidget(self.button_close)
        self.horizontalLayout_2.addWidget(self.frame_system_buttons)
        self.verticalLayout.addWidget(self.frame_header)
        self.frame_center = QtWidgets.QFrame(self.frame_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_center.sizePolicy().hasHeightForWidth())
        self.frame_center.setSizePolicy(sizePolicy)
        self.frame_center.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_center.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_center.setObjectName("frame_center")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_center)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_left_menu = QtWidgets.QFrame(self.frame_center)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_left_menu.sizePolicy().hasHeightForWidth())
        self.frame_left_menu.setSizePolicy(sizePolicy)
        self.frame_left_menu.setMinimumSize(QtCore.QSize(210, 0))
        self.frame_left_menu.setMaximumSize(QtCore.QSize(210, 16777215))
        self.frame_left_menu.setStyleSheet("background-color: rgb(27, 29, 35);")
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.button_database = QtWidgets.QPushButton(self.frame_left_menu)
        self.button_database.setGeometry(QtCore.QRect(0, 70, 210, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.button_database.setFont(font)
        self.button_database.setStyleSheet("QPushButton {\n"
"    background-position: left;\n"
"    background-repeat: no-reperat;\n"
"    background-origin: content;\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"    border: none;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(40, 44, 52);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/24x24/data/resources/icons/24x24/cil-people.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_database.setIcon(icon2)
        self.button_database.setIconSize(QtCore.QSize(24, 24))
        self.button_database.setFlat(True)
        self.button_database.setObjectName("button_database")
        self.button_device = QtWidgets.QPushButton(self.frame_left_menu)
        self.button_device.setGeometry(QtCore.QRect(0, 10, 210, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.button_device.setFont(font)
        self.button_device.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.button_device.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_device.setAutoFillBackground(False)
        self.button_device.setStyleSheet("QPushButton {\n"
"    background-position: left;\n"
"    background-repeat: no-reperat;\n"
"    background-origin: content;\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"    border: none;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(40, 44, 52);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/24x24/data/resources/icons/24x24/cil-screen-desktop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_device.setIcon(icon3)
        self.button_device.setIconSize(QtCore.QSize(24, 24))
        self.button_device.setFlat(True)
        self.button_device.setObjectName("button_device")
        self.button_statistic = QtWidgets.QPushButton(self.frame_left_menu)
        self.button_statistic.setGeometry(QtCore.QRect(0, 130, 210, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.button_statistic.setFont(font)
        self.button_statistic.setStyleSheet("QPushButton {\n"
"    background-position: left;\n"
"    background-repeat: no-reperat;\n"
"    background-origin: content;\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"    border: none;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(40, 44, 52);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/24x24/data/resources/icons/24x24/cil-chart-line.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_statistic.setIcon(icon4)
        self.button_statistic.setIconSize(QtCore.QSize(24, 24))
        self.button_statistic.setFlat(True)
        self.button_statistic.setObjectName("button_statistic")
        self.button_settings = QtWidgets.QPushButton(self.frame_left_menu)
        self.button_settings.setGeometry(QtCore.QRect(0, 640, 210, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.button_settings.setFont(font)
        self.button_settings.setStyleSheet("QPushButton {\n"
"    background-position: left;\n"
"    background-repeat: no-reperat;\n"
"    background-origin: content;\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"    border: none;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(40, 44, 52);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/24x24/data/resources/icons/24x24/cil-settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_settings.setIcon(icon5)
        self.button_settings.setIconSize(QtCore.QSize(24, 24))
        self.button_settings.setFlat(True)
        self.button_settings.setObjectName("button_settings")
        self.horizontalLayout.addWidget(self.frame_left_menu)
        self.frame_contains = QtWidgets.QFrame(self.frame_center)
        self.frame_contains.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.frame_contains.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_contains.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_contains.setObjectName("frame_contains")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_contains)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_contains)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_device = QtWidgets.QWidget()
        self.page_device.setObjectName("page_device")
        self.table_devices = QtWidgets.QTableWidget(self.page_device)
        self.table_devices.setGeometry(QtCore.QRect(20, 60, 1100, 620))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 44, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 44, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 44, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 44, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 44, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 44, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 44, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 44, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 44, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.table_devices.setPalette(palette)
        self.table_devices.setStyleSheet("QTableWidget {    \n"
"    background-color: rgb(39, 44, 54);\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    gridline-color: rgb(44, 49, 60);\n"
"    border-bottom: 1px solid rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::item{\n"
"    border-color: rgb(44, 49, 60);\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    gridline-color: rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::item:selected{\n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    height: 14px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 14px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"QHeaderView::section{\n"
"    Background-color: rgb(39, 44, 54);\n"
"    max-width: 30px;\n"
"    border: 1px solid rgb(44, 49, 60);\n"
"    border-style: none;\n"
"    border-bottom: 1px solid rgb(44, 49, 60);\n"
"    border-right: 1px solid rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::horizontalHeader {    \n"
"    background-color: rgb(81, 255, 0);\n"
"}\n"
"QHeaderView::section:horizontal\n"
"{\n"
"    border: 1px solid rgb(32, 34, 42);\n"
"    background-color: rgb(27, 29, 35);\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 3px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"}\n"
"QHeaderView::section:vertical\n"
"{\n"
"    border: 1px solid rgb(44, 49, 60);\n"
"}\n"
"")
        self.table_devices.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.table_devices.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.table_devices.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.table_devices.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_devices.setAlternatingRowColors(False)
        self.table_devices.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.table_devices.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_devices.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.table_devices.setRowCount(0)
        self.table_devices.setColumnCount(7)
        self.table_devices.setObjectName("table_devices")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/24x24/data/resources/icons/24x24/cil-uncheck-circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon6)
        self.table_devices.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        item.setFont(font)
        self.table_devices.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        item.setFont(font)
        self.table_devices.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        item.setFont(font)
        self.table_devices.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        item.setFont(font)
        self.table_devices.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        item.setFont(font)
        self.table_devices.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        item.setFont(font)
        self.table_devices.setHorizontalHeaderItem(6, item)
        self.table_devices.horizontalHeader().setVisible(True)
        self.table_devices.horizontalHeader().setCascadingSectionResizes(True)
        self.table_devices.horizontalHeader().setDefaultSectionSize(200)
        self.table_devices.horizontalHeader().setStretchLastSection(False)
        self.table_devices.verticalHeader().setVisible(False)
        self.table_devices.verticalHeader().setHighlightSections(False)
        self.table_devices.verticalHeader().setStretchLastSection(True)
        self.button_search_device = QtWidgets.QPushButton(self.page_device)
        self.button_search_device.setGeometry(QtCore.QRect(20, 10, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.button_search_device.setFont(font)
        self.button_search_device.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 10px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    color: rgb(227, 227, 227);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/16x16/data/resources/icons/16x16/cil-magnifying-glass.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_search_device.setIcon(icon7)
        self.button_search_device.setObjectName("button_search_device")
        self.button_configure_device = QtWidgets.QPushButton(self.page_device)
        self.button_configure_device.setGeometry(QtCore.QRect(130, 10, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.button_configure_device.setFont(font)
        self.button_configure_device.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 10px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    color: rgb(227, 227, 227);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/16x16/data/resources/icons/16x16/cil-equalizer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_configure_device.setIcon(icon8)
        self.button_configure_device.setObjectName("button_configure_device")
        self.button_delete_device = QtWidgets.QPushButton(self.page_device)
        self.button_delete_device.setGeometry(QtCore.QRect(240, 10, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.button_delete_device.setFont(font)
        self.button_delete_device.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 10px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    color: rgb(227, 227, 227);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/16x16/data/resources/icons/16x16/cil-remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_delete_device.setIcon(icon9)
        self.button_delete_device.setObjectName("button_delete_device")
        self.stackedWidget.addWidget(self.page_device)
        self.page_database = QtWidgets.QWidget()
        self.page_database.setObjectName("page_database")
        self.table_profiles = QtWidgets.QTableWidget(self.page_database)
        self.table_profiles.setGeometry(QtCore.QRect(330, 100, 800, 580))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 44, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 44, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 44, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 44, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 44, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 44, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 44, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 44, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 44, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.table_profiles.setPalette(palette)
        self.table_profiles.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.table_profiles.setStyleSheet("QTableWidget {    \n"
"    background-color: rgb(39, 44, 54);\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    gridline-color: rgb(44, 49, 60);\n"
"    border-bottom: 1px solid rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::item{\n"
"    border-color: rgb(44, 49, 60);\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    gridline-color: rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::item:selected{\n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    height: 14px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 14px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"QHeaderView::section{\n"
"    Background-color: rgb(39, 44, 54);\n"
"    max-width: 30px;\n"
"    border: 1px solid rgb(44, 49, 60);\n"
"    border-style: none;\n"
"    border-bottom: 1px solid rgb(44, 49, 60);\n"
"    border-right: 1px solid rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::horizontalHeader {    \n"
"    background-color: rgb(81, 255, 0);\n"
"}\n"
"QHeaderView::section:horizontal\n"
"{\n"
"    border: 1px solid rgb(32, 34, 42);\n"
"    background-color: rgb(27, 29, 35);\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 3px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"}\n"
"QHeaderView::section:vertical\n"
"{\n"
"    border: 1px solid rgb(44, 49, 60);\n"
"}\n"
"QCheckBox::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background: 3px solid rgb(52, 59, 72);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"    background-image: url(:/16x16/data/resources/icons/16x16/cil-check-alt.png);\n"
"}\n"
"")
        self.table_profiles.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.table_profiles.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.table_profiles.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.table_profiles.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_profiles.setAlternatingRowColors(False)
        self.table_profiles.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.table_profiles.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_profiles.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.table_profiles.setRowCount(0)
        self.table_profiles.setColumnCount(7)
        self.table_profiles.setObjectName("table_profiles")
        item = QtWidgets.QTableWidgetItem()
        item.setIcon(icon6)
        self.table_profiles.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_profiles.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_profiles.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_profiles.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_profiles.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_profiles.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_profiles.setHorizontalHeaderItem(6, item)
        self.table_profiles.horizontalHeader().setVisible(True)
        self.table_profiles.horizontalHeader().setCascadingSectionResizes(True)
        self.table_profiles.horizontalHeader().setDefaultSectionSize(200)
        self.table_profiles.horizontalHeader().setStretchLastSection(False)
        self.table_profiles.verticalHeader().setVisible(False)
        self.table_profiles.verticalHeader().setHighlightSections(False)
        self.table_profiles.verticalHeader().setStretchLastSection(True)
        self.button_delete_profile = QtWidgets.QPushButton(self.page_database)
        self.button_delete_profile.setGeometry(QtCore.QRect(690, 10, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.button_delete_profile.setFont(font)
        self.button_delete_profile.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 10px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    color: rgb(227, 227, 227);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.button_delete_profile.setIcon(icon9)
        self.button_delete_profile.setObjectName("button_delete_profile")
        self.button_edit_profile = QtWidgets.QPushButton(self.page_database)
        self.button_edit_profile.setGeometry(QtCore.QRect(580, 10, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.button_edit_profile.setFont(font)
        self.button_edit_profile.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.button_edit_profile.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 10px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    color: rgb(227, 227, 227);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/16x16/data/resources/icons/16x16/cil-pencil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_edit_profile.setIcon(icon10)
        self.button_edit_profile.setObjectName("button_edit_profile")
        self.button_add_profile = QtWidgets.QPushButton(self.page_database)
        self.button_add_profile.setGeometry(QtCore.QRect(470, 10, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.button_add_profile.setFont(font)
        self.button_add_profile.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 10px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    color: rgb(227, 227, 227);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/16x16/data/resources/icons/16x16/cil-plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_add_profile.setIcon(icon11)
        self.button_add_profile.setObjectName("button_add_profile")
        self.button_send_device = QtWidgets.QPushButton(self.page_database)
        self.button_send_device.setGeometry(QtCore.QRect(330, 50, 130, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.button_send_device.setFont(font)
        self.button_send_device.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 10px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    color: rgb(227, 227, 227);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/16x16/data/resources/icons/16x16/cil-paper-plane.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_send_device.setIcon(icon12)
        self.button_send_device.setObjectName("button_send_device")
        self.table_departments = QtWidgets.QTableWidget(self.page_database)
        self.table_departments.setGeometry(QtCore.QRect(10, 100, 300, 580))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 44, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 44, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 44, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 44, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 44, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 44, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 44, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 44, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 44, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.table_departments.setPalette(palette)
        self.table_departments.setStyleSheet("QTableWidget {    \n"
"    background-color: rgb(39, 44, 54);\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    gridline-color: rgb(44, 49, 60);\n"
"    border-bottom: 1px solid rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::item{\n"
"    border-color: rgb(44, 49, 60);\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    gridline-color: rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::item:selected{\n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    height: 14px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 14px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"QHeaderView::section{\n"
"    Background-color: rgb(39, 44, 54);\n"
"    max-width: 30px;\n"
"    border: 1px solid rgb(44, 49, 60);\n"
"    border-style: none;\n"
"    border-bottom: 1px solid rgb(44, 49, 60);\n"
"    border-right: 1px solid rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::horizontalHeader {    \n"
"    background-color: rgb(81, 255, 0);\n"
"}\n"
"QHeaderView::section:horizontal\n"
"{\n"
"    border: 1px solid rgb(32, 34, 42);\n"
"    background-color: rgb(27, 29, 35);\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 3px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"}\n"
"QHeaderView::section:vertical\n"
"{\n"
"    border: 1px solid rgb(44, 49, 60);\n"
"}\n"
"QCheckBox::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background: 3px solid rgb(52, 59, 72);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"    background-image: url(:/16x16/data/resources/icons/16x16/cil-check-alt.png);\n"
"}\n"
"")
        self.table_departments.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.table_departments.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.table_departments.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.table_departments.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_departments.setAlternatingRowColors(False)
        self.table_departments.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.table_departments.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_departments.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.table_departments.setRowCount(0)
        self.table_departments.setColumnCount(2)
        self.table_departments.setObjectName("table_departments")
        item = QtWidgets.QTableWidgetItem()
        item.setIcon(icon6)
        self.table_departments.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_departments.setHorizontalHeaderItem(1, item)
        self.table_departments.horizontalHeader().setVisible(True)
        self.table_departments.horizontalHeader().setCascadingSectionResizes(True)
        self.table_departments.horizontalHeader().setDefaultSectionSize(200)
        self.table_departments.horizontalHeader().setStretchLastSection(False)
        self.table_departments.verticalHeader().setVisible(False)
        self.table_departments.verticalHeader().setHighlightSections(False)
        self.table_departments.verticalHeader().setStretchLastSection(True)
        self.comboBox_databases = QtWidgets.QComboBox(self.page_database)
        self.comboBox_databases.setGeometry(QtCore.QRect(470, 50, 320, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.comboBox_databases.setFont(font)
        self.comboBox_databases.setStyleSheet("QComboBox{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}")
        self.comboBox_databases.setObjectName("comboBox_databases")
        self.button_delete_department = QtWidgets.QPushButton(self.page_database)
        self.button_delete_department.setGeometry(QtCore.QRect(120, 50, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.button_delete_department.setFont(font)
        self.button_delete_department.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 10px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    color: rgb(227, 227, 227);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.button_delete_department.setIcon(icon9)
        self.button_delete_department.setObjectName("button_delete_department")
        self.button_add_department = QtWidgets.QPushButton(self.page_database)
        self.button_add_department.setGeometry(QtCore.QRect(10, 50, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.button_add_department.setFont(font)
        self.button_add_department.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 10px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    color: rgb(227, 227, 227);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.button_add_department.setIcon(icon11)
        self.button_add_department.setObjectName("button_add_department")
        self.label = QtWidgets.QLabel(self.page_database)
        self.label.setGeometry(QtCore.QRect(330, 10, 121, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.page_database)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 121, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.button_create_pattern = QtWidgets.QPushButton(self.page_database)
        self.button_create_pattern.setGeometry(QtCore.QRect(800, 10, 150, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.button_create_pattern.setFont(font)
        self.button_create_pattern.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 10px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    color: rgb(227, 227, 227);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/16x16/data/resources/icons/16x16/cil-library-add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_create_pattern.setIcon(icon13)
        self.button_create_pattern.setObjectName("button_create_pattern")
        self.button_device_database_view = QtWidgets.QPushButton(self.page_database)
        self.button_device_database_view.setGeometry(QtCore.QRect(800, 50, 150, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.button_device_database_view.setFont(font)
        self.button_device_database_view.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 10px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    color: rgb(227, 227, 227);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/16x16/data/resources/icons/16x16/cil-user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_device_database_view.setIcon(icon14)
        self.button_device_database_view.setObjectName("button_device_database_view")
        self.button_add_profile_images = QtWidgets.QPushButton(self.page_database)
        self.button_add_profile_images.setGeometry(QtCore.QRect(960, 50, 150, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.button_add_profile_images.setFont(font)
        self.button_add_profile_images.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 10px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    color: rgb(227, 227, 227);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/16x16/data/resources/icons/16x16/cil-image-plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_add_profile_images.setIcon(icon15)
        self.button_add_profile_images.setObjectName("button_add_profile_images")
        self.button_add_profiles_group = QtWidgets.QPushButton(self.page_database)
        self.button_add_profiles_group.setGeometry(QtCore.QRect(960, 10, 150, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.button_add_profiles_group.setFont(font)
        self.button_add_profiles_group.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 10px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    color: rgb(227, 227, 227);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/16x16/data/resources/icons/16x16/cil-notes.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_add_profiles_group.setIcon(icon16)
        self.button_add_profiles_group.setObjectName("button_add_profiles_group")
        self.stackedWidget.addWidget(self.page_database)
        self.page_statistic = QtWidgets.QWidget()
        self.page_statistic.setObjectName("page_statistic")
        self.table_statistics = QtWidgets.QTableWidget(self.page_statistic)
        self.table_statistics.setGeometry(QtCore.QRect(10, 170, 630, 520))
        self.table_statistics.setStyleSheet("QTableWidget {    \n"
"    background-color: rgb(39, 44, 54);\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    gridline-color: rgb(44, 49, 60);\n"
"    border-bottom: 1px solid rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::item{\n"
"    border-color: rgb(44, 49, 60);\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    gridline-color: rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::item:selected{\n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    height: 14px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 14px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"QHeaderView::section{\n"
"    Background-color: rgb(39, 44, 54);\n"
"    max-width: 30px;\n"
"    border: 1px solid rgb(44, 49, 60);\n"
"    border-style: none;\n"
"    border-bottom: 1px solid rgb(44, 49, 60);\n"
"    border-right: 1px solid rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::horizontalHeader {    \n"
"    background-color: rgb(81, 255, 0);\n"
"}\n"
"QHeaderView::section:horizontal\n"
"{\n"
"    border: 1px solid rgb(32, 34, 42);\n"
"    background-color: rgb(27, 29, 35);\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 3px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"}\n"
"QHeaderView::section:vertical\n"
"{\n"
"    border: 1px solid rgb(44, 49, 60);\n"
"}\n"
"")
        self.table_statistics.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_statistics.setObjectName("table_statistics")
        self.table_statistics.setColumnCount(5)
        self.table_statistics.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_statistics.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_statistics.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_statistics.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_statistics.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_statistics.setHorizontalHeaderItem(4, item)
        self.table_statistics.verticalHeader().setVisible(False)
        self.dateTimeEdit_start = QtWidgets.QDateTimeEdit(self.page_statistic)
        self.dateTimeEdit_start.setGeometry(QtCore.QRect(200, 50, 170, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.dateTimeEdit_start.setFont(font)
        self.dateTimeEdit_start.setStyleSheet("QDateTimeEdit{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QDateTimeEdit:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QDateTimeEdit QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}")
        self.dateTimeEdit_start.setMinimumDate(QtCore.QDate(2020, 1, 1))
        self.dateTimeEdit_start.setCalendarPopup(True)
        self.dateTimeEdit_start.setObjectName("dateTimeEdit_start")
        self.dateTimeEdit_end = QtWidgets.QDateTimeEdit(self.page_statistic)
        self.dateTimeEdit_end.setGeometry(QtCore.QRect(440, 50, 170, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.dateTimeEdit_end.setFont(font)
        self.dateTimeEdit_end.setStyleSheet("QDateTimeEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding-left: 10px;\n"
"}\n"
"QDateTimeEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QDateTimeEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}")
        self.dateTimeEdit_end.setMinimumDate(QtCore.QDate(2020, 1, 1))
        self.dateTimeEdit_end.setCalendarPopup(True)
        self.dateTimeEdit_end.setObjectName("dateTimeEdit_end")
        self.label_start_time = QtWidgets.QLabel(self.page_statistic)
        self.label_start_time.setGeometry(QtCore.QRect(150, 50, 40, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label_start_time.setFont(font)
        self.label_start_time.setObjectName("label_start_time")
        self.label_end_time = QtWidgets.QLabel(self.page_statistic)
        self.label_end_time.setGeometry(QtCore.QRect(390, 50, 40, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label_end_time.setFont(font)
        self.label_end_time.setObjectName("label_end_time")
        self.radiobutton_time = QtWidgets.QRadioButton(self.page_statistic)
        self.radiobutton_time.setGeometry(QtCore.QRect(10, 50, 120, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.radiobutton_time.setFont(font)
        self.radiobutton_time.setStyleSheet("")
        self.radiobutton_time.setChecked(False)
        self.radiobutton_time.setObjectName("radiobutton_time")
        self.radiobutton_temperature = QtWidgets.QRadioButton(self.page_statistic)
        self.radiobutton_temperature.setGeometry(QtCore.QRect(10, 90, 120, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.radiobutton_temperature.setFont(font)
        self.radiobutton_temperature.setObjectName("radiobutton_temperature")
        self.label_min_temperature = QtWidgets.QLabel(self.page_statistic)
        self.label_min_temperature.setGeometry(QtCore.QRect(150, 90, 40, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label_min_temperature.setFont(font)
        self.label_min_temperature.setObjectName("label_min_temperature")
        self.doubleSpinBox_min_temperature = QtWidgets.QDoubleSpinBox(self.page_statistic)
        self.doubleSpinBox_min_temperature.setGeometry(QtCore.QRect(200, 90, 90, 30))
        self.doubleSpinBox_min_temperature.setStyleSheet("QDoubleSpinBox {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding-left: 10px;\n"
"}\n"
"QDoubleSpinBox:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QDoubleSpinBox:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}")
        self.doubleSpinBox_min_temperature.setMinimum(35.0)
        self.doubleSpinBox_min_temperature.setMaximum(40.0)
        self.doubleSpinBox_min_temperature.setSingleStep(0.1)
        self.doubleSpinBox_min_temperature.setObjectName("doubleSpinBox_min_temperature")
        self.doubleSpinBox_max_temperature = QtWidgets.QDoubleSpinBox(self.page_statistic)
        self.doubleSpinBox_max_temperature.setGeometry(QtCore.QRect(440, 90, 90, 30))
        self.doubleSpinBox_max_temperature.setStyleSheet("QDoubleSpinBox {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding-left: 10px;\n"
"}\n"
"QDoubleSpinBox:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QDoubleSpinBox:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}")
        self.doubleSpinBox_max_temperature.setMinimum(35.0)
        self.doubleSpinBox_max_temperature.setMaximum(40.0)
        self.doubleSpinBox_max_temperature.setSingleStep(0.1)
        self.doubleSpinBox_max_temperature.setProperty("value", 40.0)
        self.doubleSpinBox_max_temperature.setObjectName("doubleSpinBox_max_temperature")
        self.label_max_temperature = QtWidgets.QLabel(self.page_statistic)
        self.label_max_temperature.setGeometry(QtCore.QRect(390, 90, 40, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label_max_temperature.setFont(font)
        self.label_max_temperature.setObjectName("label_max_temperature")
        self.button_search_statistics = QtWidgets.QPushButton(self.page_statistic)
        self.button_search_statistics.setGeometry(QtCore.QRect(10, 130, 120, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.button_search_statistics.setFont(font)
        self.button_search_statistics.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 10px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    color: rgb(227, 227, 227);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.button_search_statistics.setIcon(icon7)
        self.button_search_statistics.setObjectName("button_search_statistics")
        self.comboBox_profiles = QtWidgets.QComboBox(self.page_statistic)
        self.comboBox_profiles.setGeometry(QtCore.QRect(10, 10, 360, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.comboBox_profiles.setFont(font)
        self.comboBox_profiles.setStyleSheet("QComboBox{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}")
        self.comboBox_profiles.setObjectName("comboBox_profiles")
        self.button_person_plot = QtWidgets.QPushButton(self.page_statistic)
        self.button_person_plot.setGeometry(QtCore.QRect(380, 10, 120, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.button_person_plot.setFont(font)
        self.button_person_plot.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 10px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    color: rgb(227, 227, 227);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/16x16/data/resources/icons/16x16/cil-chart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_person_plot.setIcon(icon17)
        self.button_person_plot.setObjectName("button_person_plot")
        self.button_all_statistic = QtWidgets.QPushButton(self.page_statistic)
        self.button_all_statistic.setGeometry(QtCore.QRect(140, 130, 120, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.button_all_statistic.setFont(font)
        self.button_all_statistic.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 10px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    color: rgb(227, 227, 227);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/16x16/data/resources/icons/16x16/cil-reload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_all_statistic.setIcon(icon18)
        self.button_all_statistic.setObjectName("button_all_statistic")
        self.button_report = QtWidgets.QPushButton(self.page_statistic)
        self.button_report.setGeometry(QtCore.QRect(510, 10, 120, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.button_report.setFont(font)
        self.button_report.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 10px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    color: rgb(227, 227, 227);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.button_report.setIcon(icon16)
        self.button_report.setObjectName("button_report")
        self.button_strangers_statistic = QtWidgets.QPushButton(self.page_statistic)
        self.button_strangers_statistic.setGeometry(QtCore.QRect(270, 130, 140, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.button_strangers_statistic.setFont(font)
        self.button_strangers_statistic.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 10px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    color: rgb(227, 227, 227);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/16x16/data/resources/icons/16x16/cil-chart-pie.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_strangers_statistic.setIcon(icon19)
        self.button_strangers_statistic.setObjectName("button_strangers_statistic")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.page_statistic)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(650, 50, 491, 311))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_pie_person_passage_day = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_pie_person_passage_day.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_pie_person_passage_day.setObjectName("verticalLayout_pie_person_passage_day")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.page_statistic)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(650, 370, 491, 311))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_pie_person_passage_alltime = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_pie_person_passage_alltime.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_pie_person_passage_alltime.setObjectName("verticalLayout_pie_person_passage_alltime")
        self.stackedWidget.addWidget(self.page_statistic)
        self.page_settings = QtWidgets.QWidget()
        self.page_settings.setObjectName("page_settings")
        self.stackedWidget.addWidget(self.page_settings)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.frame_statusbar = QtWidgets.QFrame(self.frame_contains)
        self.frame_statusbar.setMinimumSize(QtCore.QSize(0, 25))
        self.frame_statusbar.setMaximumSize(QtCore.QSize(16777215, 25))
        self.frame_statusbar.setStyleSheet("background-color: rgb(27, 29, 35);")
        self.frame_statusbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_statusbar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_statusbar.setObjectName("frame_statusbar")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_statusbar)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_statusbar = QtWidgets.QLabel(self.frame_statusbar)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(False)
        font.setWeight(50)
        self.label_statusbar.setFont(font)
        self.label_statusbar.setObjectName("label_statusbar")
        self.horizontalLayout_4.addWidget(self.label_statusbar)
        self.verticalLayout_2.addWidget(self.frame_statusbar)
        self.horizontalLayout.addWidget(self.frame_contains)
        self.verticalLayout.addWidget(self.frame_center)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Thermal Camera\'s Manager"))
        self.label_title.setText(_translate("MainWindow", "Thermal Camera\'s Manager"))
        self.button_minimize.setToolTip(_translate("MainWindow", "Minimize"))
        self.button_close.setToolTip(_translate("MainWindow", "Close"))
        self.button_database.setText(_translate("MainWindow", "Database Manager"))
        self.button_device.setText(_translate("MainWindow", "Device Manager"))
        self.button_statistic.setText(_translate("MainWindow", "Statistic"))
        self.button_settings.setText(_translate("MainWindow", "Settings"))
        item = self.table_devices.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Device Name"))
        item = self.table_devices.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Model"))
        item = self.table_devices.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Serial Number"))
        item = self.table_devices.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "MAC-Address"))
        item = self.table_devices.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "IP Address"))
        item = self.table_devices.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "State"))
        self.button_search_device.setText(_translate("MainWindow", "Search"))
        self.button_configure_device.setText(_translate("MainWindow", "Configure"))
        self.button_delete_device.setText(_translate("MainWindow", "Delete"))
        self.table_profiles.setSortingEnabled(False)
        item = self.table_profiles.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ID"))
        item = self.table_profiles.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Image"))
        item = self.table_profiles.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Name"))
        item = self.table_profiles.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Department"))
        item = self.table_profiles.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Gender"))
        item = self.table_profiles.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Phone Number"))
        self.button_delete_profile.setText(_translate("MainWindow", "Delete"))
        self.button_edit_profile.setText(_translate("MainWindow", "Edit"))
        self.button_add_profile.setText(_translate("MainWindow", "Add"))
        self.button_send_device.setText(_translate("MainWindow", "Send to Device"))
        item = self.table_departments.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Department"))
        self.button_delete_department.setText(_translate("MainWindow", "Delete"))
        self.button_add_department.setText(_translate("MainWindow", "Add"))
        self.label.setText(_translate("MainWindow", "Profiles DB"))
        self.label_2.setText(_translate("MainWindow", "Departments DB"))
        self.button_create_pattern.setText(_translate("MainWindow", "Create Pattern"))
        self.button_device_database_view.setText(_translate("MainWindow", "Database View"))
        self.button_add_profile_images.setText(_translate("MainWindow", "Add Profile Images"))
        self.button_add_profiles_group.setText(_translate("MainWindow", "Add Profiles Group"))
        self.table_statistics.setSortingEnabled(True)
        item = self.table_statistics.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.table_statistics.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.table_statistics.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Datetime"))
        item = self.table_statistics.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Tempeature"))
        item = self.table_statistics.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Similar"))
        self.dateTimeEdit_start.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd HH:mm"))
        self.dateTimeEdit_end.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd HH:mm"))
        self.label_start_time.setText(_translate("MainWindow", "Start"))
        self.label_end_time.setText(_translate("MainWindow", "End"))
        self.radiobutton_time.setText(_translate("MainWindow", "Time"))
        self.radiobutton_temperature.setText(_translate("MainWindow", "Temperature"))
        self.label_min_temperature.setText(_translate("MainWindow", "Min"))
        self.label_max_temperature.setText(_translate("MainWindow", "Max"))
        self.button_search_statistics.setText(_translate("MainWindow", "Search"))
        self.button_person_plot.setText(_translate("MainWindow", "Charts"))
        self.button_all_statistic.setText(_translate("MainWindow", "All Statistic"))
        self.button_report.setText(_translate("MainWindow", "Report"))
        self.button_strangers_statistic.setText(_translate("MainWindow", "Strangers Statistic"))
        self.label_statusbar.setText(_translate("MainWindow", "MetallicAlex"))
import files_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
