# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_list_device.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ListDeviceForm(object):
    def setupUi(self, ListDeviceForm):
        ListDeviceForm.setObjectName("ListDeviceForm")
        ListDeviceForm.resize(400, 300)
        ListDeviceForm.setWindowFlag(QtCore.Qt.FramelessWindowHint)
        ListDeviceForm.setStyleSheet("/* SCROLL BARS */\n"
                                     "QScrollBar:horizontal {\n"
                                     "    border: none;\n"
                                     "    background: rgb(52, 59, 72);\n"
                                     "    height: 14px;\n"
                                     "    margin: 0px 21px 0 21px;\n"
                                     "    border-radius: 0px;\n"
                                     "}\n"
                                     "QScrollBar::handle:horizontal {\n"
                                     "    background: #87B9E0;\n"
                                     "    min-width: 25px;\n"
                                     "    border-radius: 7px\n"
                                     "}\n"
                                     "QScrollBar::add-line:horizontal {\n"
                                     "    border: none;\n"
                                     "    background: #0C5DB9;\n"
                                     "    width: 20px;\n"
                                     "    border-top-right-radius: 7px;\n"
                                     "    border-bottom-right-radius: 7px;\n"
                                     "    subcontrol-position: right;\n"
                                     "    subcontrol-origin: margin;\n"
                                     "}\n"
                                     "QScrollBar::sub-line:horizontal {\n"
                                     "    border: none;\n"
                                     "    background: #0C5DB9;\n"
                                     "    width: 20px;\n"
                                     "    border-top-left-radius: 7px;\n"
                                     "    border-bottom-left-radius: 7px;\n"
                                     "    subcontrol-position: left;\n"
                                     "    subcontrol-origin: margin;\n"
                                     "}\n"
                                     "QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
                                     "{\n"
                                     "     background: none;\n"
                                     "}\n"
                                     "QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
                                     "{\n"
                                     "     background: none;\n"
                                     "}\n"
                                     " QScrollBar:vertical {\n"
                                     "    border: none;\n"
                                     "    background: rgb(52, 59, 72);\n"
                                     "    width: 14px;\n"
                                     "    margin: 21px 0 21px 0;\n"
                                     "    border-radius: 0px;\n"
                                     " }\n"
                                     " QScrollBar::handle:vertical {    \n"
                                     "    background: #87B9E0;\n"
                                     "    min-height: 25px;\n"
                                     "    border-radius: 7px\n"
                                     " }\n"
                                     " QScrollBar::add-line:vertical {\n"
                                     "     border: none;\n"
                                     "    background: #0C5DB9;\n"
                                     "     height: 20px;\n"
                                     "    border-bottom-left-radius: 7px;\n"
                                     "    border-bottom-right-radius: 7px;\n"
                                     "     subcontrol-position: bottom;\n"
                                     "     subcontrol-origin: margin;\n"
                                     " }\n"
                                     " QScrollBar::sub-line:vertical {\n"
                                     "    border: none;\n"
                                     "    background: #0C5DB9;\n"
                                     "     height: 20px;\n"
                                     "    border-top-left-radius: 7px;\n"
                                     "    border-top-right-radius: 7px;\n"
                                     "     subcontrol-position: top;\n"
                                     "     subcontrol-origin: margin;\n"
                                     " }\n"
                                     " QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
                                     "     background: none;\n"
                                     " }\n"
                                     "\n"
                                     " QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
                                     "     background: none;\n"
                                     " }\n"
                                     "\n"
                                     "/* CHECKBOX */\n"
                                     "QCheckbox {\n"
                                     "    background: #91D1EE;\n"
                                     "}\n"
                                     "QCheckBox::indicator {\n"
                                     "    border: 3px solid rgb(255,255,255,221);\n"
                                     "    width: 15px;\n"
                                     "    height: 15px;\n"
                                     "    border-radius: 10px;\n"
                                     "    background: #91D1EE;\n"
                                     "}\n"
                                     "QCheckBox::indicator:hover {\n"
                                     "    border: 3px solid rgb(255,255,255,221);\n"
                                     "}\n"
                                     "QCheckBox::indicator:checked {\n"
                                     "    background: 1px solid #91D1EE;\n"
                                     "    border: 1px solid rgb(255,255,255,221);\n"
                                     "    background-image: url(:/16x16/data/resources/icons/16x16/cil-check-alt.png);\n"
                                     "}")
        self.verticalLayout = QtWidgets.QVBoxLayout(ListDeviceForm)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_center = QtWidgets.QFrame(ListDeviceForm)
        self.frame_center.setStyleSheet("background-color: #0C5DB9;\n"
                                        "")
        self.frame_center.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_center.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_center.setObjectName("frame_center")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_center)
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_title = QtWidgets.QFrame(self.frame_center)
        self.frame_title.setMaximumSize(QtCore.QSize(400, 42))
        self.frame_title.setStyleSheet("background-color: #0C5DB9;")
        self.frame_title.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setLineWidth(0)
        self.frame_title.setObjectName("frame_title")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_title)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_title = QtWidgets.QLabel(self.frame_title)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_title.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("background: transparent;\n"
                                       "color: rgb(255, 255, 255, 221);")
        self.label_title.setObjectName("label_title")
        self.horizontalLayout_3.addWidget(self.label_title)
        self.button_close = QtWidgets.QPushButton(self.frame_title)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_close.sizePolicy().hasHeightForWidth())
        self.button_close.setSizePolicy(sizePolicy)
        self.button_close.setMinimumSize(QtCore.QSize(40, 0))
        self.button_close.setMaximumSize(QtCore.QSize(40, 16777215))
        self.button_close.setStyleSheet("QPushButton {    \n"
                                        "    border: none;\n"
                                        "    background-color: transparent;\n"
                                        "}\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: #B9400C;\n"
                                        "}\n"
                                        "QPushButton:pressed {    \n"
                                        "    background-color: #D04B4B;\n"
                                        "}")
        self.button_close.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/20x20/data/resources/icons/20x20/cil-x.png"), QtGui.QIcon.Normal,
                       QtGui.QIcon.Off)
        self.button_close.setIcon(icon)
        self.button_close.setObjectName("button_close")
        self.horizontalLayout_3.addWidget(self.button_close)
        self.verticalLayout_2.addWidget(self.frame_title)
        self.frame_contains = QtWidgets.QFrame(self.frame_center)
        self.frame_contains.setStyleSheet("background-color: #EFF7FD;")
        self.frame_contains.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_contains.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_contains.setObjectName("frame_contains")
        self.button_accept = QtWidgets.QPushButton(self.frame_contains)
        self.button_accept.setGeometry(QtCore.QRect(224, 210, 150, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.button_accept.setFont(font)
        self.button_accept.setStyleSheet("QPushButton {\n"
                                         "    border-radius: 10px;    \n"
                                         "    background-color: #0CB53B;\n"
                                         "    color: rgb(255, 255, 255, 221);\n"
                                         "}\n"
                                         "QPushButton:hover {\n"
                                         "    background-color: #009229;\n"
                                         "    color: rgb(255, 255, 255, 221);\n"
                                         "}\n"
                                         "QPushButton:pressed {    \n"
                                         "    background-color: #00C838;\n"
                                         "    color: rgb(255, 255, 255);\n"
                                         "}")
        self.button_accept.setObjectName("button_accept")
        self.button_cancel = QtWidgets.QPushButton(self.frame_contains)
        self.button_cancel.setGeometry(QtCore.QRect(20, 210, 150, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.button_cancel.setFont(font)
        self.button_cancel.setStyleSheet("QPushButton {\n"
                                         "    border-radius: 10px;    \n"
                                         "    background-color: #B9400C;\n"
                                         "    color: rgb(255, 255, 255, 221);\n"
                                         "}\n"
                                         "QPushButton:hover {\n"
                                         "    background-color: #8A0000;\n"
                                         "    color: rgb(255, 255, 255, 221);\n"
                                         "}\n"
                                         "QPushButton:pressed {    \n"
                                         "    background-color: #D04B4B;\n"
                                         "    color: rgb(255, 255, 255);\n"
                                         "}")
        self.button_cancel.setObjectName("button_cancel")
        self.table_devices = QtWidgets.QTableWidget(self.frame_contains)
        self.table_devices.setGeometry(QtCore.QRect(20, 10, 354, 192))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(9, 55, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(9, 55, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(9, 55, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(228, 242, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(9, 55, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(9, 55, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(9, 55, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(228, 242, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(9, 55, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(9, 55, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(9, 55, 107))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(228, 242, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.table_devices.setPalette(palette)
        self.table_devices.setStyleSheet("QTableWidget {    \n"
                                         "    background-color: #FFFFFF;\n"
                                         "    alternate-background-color: #E4F2FD;\n"
                                         "    gridline-color: #91D1EE;\n"
                                         "    color: #09376B;\n"
                                         "}\n"
                                         "QTableWidget::item{\n"
                                         "    gridline-color: #91D1EE;\n"
                                         "}\n"
                                         "QTableWidget::item:selected{\n"
                                         "    background-color: #2894D4;\n"
                                         "    color: #FFFFFF;\n"
                                         "}\n"
                                         "QScrollBar:horizontal {\n"
                                         "    border: none;\n"
                                         "    background: #EFF7FD;\n"
                                         "    height: 14px;\n"
                                         "    margin: 0px 21px 0 21px;\n"
                                         "    border-radius: 0px;\n"
                                         "}\n"
                                         " QScrollBar:vertical {\n"
                                         "    border: none;\n"
                                         "    background: #EFF7FD;\n"
                                         "    width: 14px;\n"
                                         "    margin: 21px 0 21px 0;\n"
                                         "    border-radius: 0px;\n"
                                         " }\n"
                                         "QHeaderView::section{\n"
                                         "    Background-color: #91D1EE;\n"
                                         "    max-width: 30px;\n"
                                         "    border: 1px solid #91D1EE;\n"
                                         "    border-style: none;\n"
                                         "    border: 1px solid #91D1EE;\n"
                                         "}\n"
                                         "QTableWidget::horizontalHeader {    \n"
                                         "    background-color: #FFFFFF;\n"
                                         "}\n"
                                         "QHeaderView::section:horizontal\n"
                                         "{\n"
                                         "    background-color: #91D1EE;\n"
                                         "    color: rgb(255, 255, 255);\n"
                                         "    border: 1px solid #91D1EE;\n"
                                         "}\n"
                                         "")
        self.table_devices.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.table_devices.setFrameShadow(QtWidgets.QFrame.Plain)
        self.table_devices.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.table_devices.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.table_devices.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_devices.setAlternatingRowColors(True)
        self.table_devices.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.table_devices.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_devices.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.table_devices.setShowGrid(False)
        self.table_devices.setRowCount(0)
        self.table_devices.setColumnCount(3)
        self.table_devices.setObjectName("table_devices")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignVCenter)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/24x24/data/resources/icons/24x24/cil-uncheck-circle.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        item.setIcon(icon1)
        self.table_devices.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        item.setFont(font)
        self.table_devices.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        item.setFont(font)
        self.table_devices.setHorizontalHeaderItem(2, item)
        self.table_devices.horizontalHeader().setVisible(True)
        self.table_devices.horizontalHeader().setCascadingSectionResizes(True)
        self.table_devices.horizontalHeader().setDefaultSectionSize(200)
        self.table_devices.horizontalHeader().setStretchLastSection(True)
        self.table_devices.verticalHeader().setVisible(False)
        self.table_devices.verticalHeader().setHighlightSections(False)
        self.table_devices.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_2.addWidget(self.frame_contains)
        self.verticalLayout.addWidget(self.frame_center)

        self.retranslateUi(ListDeviceForm)
        QtCore.QMetaObject.connectSlotsByName(ListDeviceForm)

    def retranslateUi(self, ListDeviceForm):
        _translate = QtCore.QCoreApplication.translate
        ListDeviceForm.setWindowTitle(_translate("ListDeviceForm", "Список устройств"))
        self.label_title.setText(_translate("ListDeviceForm", "Список устройств"))
        self.button_close.setToolTip(_translate("ListDeviceForm", "Close"))
        self.button_accept.setText(_translate("ListDeviceForm", "Добавить"))
        self.button_cancel.setText(_translate("ListDeviceForm", "Отмена"))
        item = self.table_devices.horizontalHeaderItem(1)
        item.setText(_translate("ListDeviceForm", "Название"))
        item = self.table_devices.horizontalHeaderItem(2)
        item.setText(_translate("ListDeviceForm", "Серийный номер"))

