# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_device_database_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormDeviceDatabaseView(object):
    def setupUi(self, FormDeviceDatabaseView):
        FormDeviceDatabaseView.setObjectName("FormDeviceDatabaseView")
        FormDeviceDatabaseView.resize(600, 700)
        FormDeviceDatabaseView.setWindowFlag(QtCore.Qt.FramelessWindowHint)
        FormDeviceDatabaseView.setStyleSheet("background-color: rgb(27, 29, 35);")
        self.frame_main = QtWidgets.QFrame(FormDeviceDatabaseView)
        self.frame_main.setGeometry(QtCore.QRect(0, 0, 600, 700))
        self.frame_main.setMinimumSize(QtCore.QSize(600, 700))
        self.frame_main.setStyleSheet("/* LINE EDIT */\n"
                                      "QLineEdit {\n"
                                      "    background-color: rgb(27, 29, 35);\n"
                                      "    border-radius: 5px;\n"
                                      "    border: 2px solid rgb(27, 29, 35);\n"
                                      "    padding-left: 10px;\n"
                                      "}\n"
                                      "QLineEdit:hover {\n"
                                      "    border: 2px solid rgb(64, 71, 88);\n"
                                      "}\n"
                                      "QLineEdit:focus {\n"
                                      "    border: 2px solid rgb(91, 101, 124);\n"
                                      "}\n"
                                      "\n"
                                      "/* SCROLL BARS */\n"
                                      "QScrollBar:horizontal {\n"
                                      "    border: none;\n"
                                      "    background: rgb(52, 59, 72);\n"
                                      "    height: 14px;\n"
                                      "    margin: 0px 21px 0 21px;\n"
                                      "    border-radius: 0px;\n"
                                      "}\n"
                                      "QScrollBar::handle:horizontal {\n"
                                      "    background: rgb(85, 170, 255);\n"
                                      "    min-width: 25px;\n"
                                      "    border-radius: 7px\n"
                                      "}\n"
                                      "QScrollBar::add-line:horizontal {\n"
                                      "    border: none;\n"
                                      "    background: rgb(55, 63, 77);\n"
                                      "    width: 20px;\n"
                                      "    border-top-right-radius: 7px;\n"
                                      "    border-bottom-right-radius: 7px;\n"
                                      "    subcontrol-position: right;\n"
                                      "    subcontrol-origin: margin;\n"
                                      "}\n"
                                      "QScrollBar::sub-line:horizontal {\n"
                                      "    border: none;\n"
                                      "    background: rgb(55, 63, 77);\n"
                                      "    width: 20px;\n"
                                      "    border-top-left-radius: 7px;\n"
                                      "    border-bottom-left-radius: 7px;\n"
                                      "    subcontrol-position: left;\n"
                                      "    subcontrol-origin: margin;\n"
                                      "}\n"
                                      "QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
                                      "{\n"
                                      "     background: none;\n"
                                      "}\n"
                                      "QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
                                      "{\n"
                                      "     background: none;\n"
                                      "}\n"
                                      " QScrollBar:vertical {\n"
                                      "    border: none;\n"
                                      "    background: rgb(52, 59, 72);\n"
                                      "    width: 14px;\n"
                                      "    margin: 21px 0 21px 0;\n"
                                      "    border-radius: 0px;\n"
                                      " }\n"
                                      " QScrollBar::handle:vertical {    \n"
                                      "    background: rgb(85, 170, 255);\n"
                                      "    min-height: 25px;\n"
                                      "    border-radius: 7px\n"
                                      " }\n"
                                      " QScrollBar::add-line:vertical {\n"
                                      "     border: none;\n"
                                      "    background: rgb(55, 63, 77);\n"
                                      "     height: 20px;\n"
                                      "    border-bottom-left-radius: 7px;\n"
                                      "    border-bottom-right-radius: 7px;\n"
                                      "     subcontrol-position: bottom;\n"
                                      "     subcontrol-origin: margin;\n"
                                      " }\n"
                                      " QScrollBar::sub-line:vertical {\n"
                                      "    border: none;\n"
                                      "    background: rgb(55, 63, 77);\n"
                                      "     height: 20px;\n"
                                      "    border-top-left-radius: 7px;\n"
                                      "    border-top-right-radius: 7px;\n"
                                      "     subcontrol-position: top;\n"
                                      "     subcontrol-origin: margin;\n"
                                      " }\n"
                                      " QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
                                      "     background: none;\n"
                                      " }\n"
                                      "\n"
                                      " QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
                                      "     background: none;\n"
                                      " }\n"
                                      "\n"
                                      "/* CHECKBOX */\n"
                                      "QCheckBox::indicator {\n"
                                      "    border: 3px solid rgb(52, 59, 72);\n"
                                      "    width: 15px;\n"
                                      "    height: 15px;\n"
                                      "    border-radius: 10px;\n"
                                      "    background: rgb(44, 49, 60);\n"
                                      "}\n"
                                      "QCheckBox::indicator:hover {\n"
                                      "    border: 3px solid rgb(58, 66, 81);\n"
                                      "}\n"
                                      "QCheckBox::indicator:checked {\n"
                                      "    background: 3px solid rgb(52, 59, 72);\n"
                                      "    border: 3px solid rgb(52, 59, 72);    \n"
                                      "    background-image: url(:/16x16/data/resources/icons/16x16/cil-check-alt.png);\n"
                                      "}\n"
                                      "\n"
                                      "/* RADIO BUTTON */\n"
                                      "QRadioButton::indicator {\n"
                                      "    border: 3px solid rgb(52, 59, 72);\n"
                                      "    width: 15px;\n"
                                      "    height: 15px;\n"
                                      "    border-radius: 10px;\n"
                                      "    background: rgb(44, 49, 60);\n"
                                      "}\n"
                                      "QRadioButton::indicator:hover {\n"
                                      "    border: 3px solid rgb(58, 66, 81);\n"
                                      "}\n"
                                      "QRadioButton::indicator:checked {\n"
                                      "    background: 3px solid rgb(94, 106, 130);\n"
                                      "    border: 3px solid rgb(52, 59, 72);    \n"
                                      "}\n"
                                      "\n"
                                      "/* COMBOBOX */\n"
                                      "QComboBox{\n"
                                      "    background-color: rgb(27, 29, 35);\n"
                                      "    border-radius: 5px;\n"
                                      "    border: 2px solid rgb(27, 29, 35);\n"
                                      "    padding: 5px;\n"
                                      "    padding-left: 10px;\n"
                                      "}\n"
                                      "QComboBox:hover{\n"
                                      "    border: 2px solid rgb(64, 71, 88);\n"
                                      "}\n"
                                      "QComboBox::drop-down {\n"
                                      "    subcontrol-origin: padding;\n"
                                      "    subcontrol-position: top right;\n"
                                      "    width: 25px; \n"
                                      "    border-left-width: 3px;\n"
                                      "    border-left-color: rgba(39, 44, 54, 150);\n"
                                      "    border-left-style: solid;\n"
                                      "    border-top-right-radius: 3px;\n"
                                      "    border-bottom-right-radius: 3px;    \n"
                                      "    background-image: url(:/16x16/data/resources/icons/16x16/cil-arrow-bottom.png);\n"
                                      "    background-position: center;\n"
                                      "    background-repeat: no-reperat;\n"
                                      " }\n"
                                      "QComboBox QAbstractItemView {\n"
                                      "    color: rgb(85, 170, 255);    \n"
                                      "    background-color: rgb(27, 29, 35);\n"
                                      "    padding: 10px;\n"
                                      "    selection-background-color: rgb(39, 44, 54);\n"
                                      "}\n"
                                      "\n"
                                      "/* SLIDERS */\n"
                                      "QSlider::groove:horizontal {\n"
                                      "    border-radius: 9px;\n"
                                      "    height: 18px;\n"
                                      "    margin: 0px;\n"
                                      "    background-color: rgb(52, 59, 72);\n"
                                      "}\n"
                                      "QSlider::groove:horizontal:hover {\n"
                                      "    background-color: rgb(55, 62, 76);\n"
                                      "}\n"
                                      "QSlider::handle:horizontal {\n"
                                      "    background-color: rgb(85, 170, 255);\n"
                                      "    border: none;\n"
                                      "    height: 18px;\n"
                                      "    width: 18px;\n"
                                      "    margin: 0px;\n"
                                      "    border-radius: 9px;\n"
                                      "}\n"
                                      "QSlider::handle:horizontal:hover {\n"
                                      "    background-color: rgb(105, 180, 255);\n"
                                      "}\n"
                                      "QSlider::handle:horizontal:pressed {\n"
                                      "    background-color: rgb(65, 130, 195);\n"
                                      "}\n"
                                      "\n"
                                      "QSlider::groove:vertical {\n"
                                      "    border-radius: 9px;\n"
                                      "    width: 18px;\n"
                                      "    margin: 0px;\n"
                                      "    background-color: rgb(52, 59, 72);\n"
                                      "}\n"
                                      "QSlider::groove:vertical:hover {\n"
                                      "    background-color: rgb(55, 62, 76);\n"
                                      "}\n"
                                      "QSlider::handle:vertical {\n"
                                      "    background-color: rgb(85, 170, 255);\n"
                                      "    border: none;\n"
                                      "    height: 18px;\n"
                                      "    width: 18px;\n"
                                      "    margin: 0px;\n"
                                      "    border-radius: 9px;\n"
                                      "}\n"
                                      "QSlider::handle:vertical:hover {\n"
                                      "    background-color: rgb(105, 180, 255);\n"
                                      "}\n"
                                      "QSlider::handle:vertical:pressed {\n"
                                      "    background-color: rgb(65, 130, 195);\n"
                                      "}\n"
                                      "\n"
                                      ""
                                      "QToolTip {"
                                      "color: #ffffff;"
                                      "background-color: rgba(27, 29, 35, 160);"
                                      "border: 1px solid rgb(40, 40, 40);"
                                      "border-radius: 2px;"
                                      "}"
                                      )
        self.frame_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_main)
        self.verticalLayout.setContentsMargins(5, 0, 5, 5)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_header = QtWidgets.QFrame(self.frame_main)
        self.frame_header.setMinimumSize(QtCore.QSize(600, 42))
        self.frame_header.setMaximumSize(QtCore.QSize(600, 42))
        self.frame_header.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_header.setObjectName("frame_header")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_header)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_title = QtWidgets.QLabel(self.frame_header)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 29, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 29, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 29, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 29, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 29, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 29, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 29, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 29, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 29, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_title.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("")
        self.label_title.setObjectName("label_title")
        self.horizontalLayout.addWidget(self.label_title)
        self.button_close = QtWidgets.QPushButton(self.frame_header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_close.sizePolicy().hasHeightForWidth())
        self.button_close.setSizePolicy(sizePolicy)
        self.button_close.setMinimumSize(QtCore.QSize(40, 0))
        self.button_close.setMaximumSize(QtCore.QSize(40, 16777215))
        self.button_close.setStyleSheet("QPushButton {    \n"
                                        "    border: none;\n"
                                        "    background-color: transparent;\n"
                                        "}\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: rgb(52, 59, 72);\n"
                                        "}\n"
                                        "QPushButton:pressed {    \n"
                                        "    background-color: rgb(85, 170, 255);\n"
                                        "}")
        self.button_close.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/20x20/data/resources/icons/20x20/cil-x.png"), QtGui.QIcon.Normal,
                       QtGui.QIcon.Off)
        self.button_close.setIcon(icon)
        self.button_close.setObjectName("button_close")
        self.horizontalLayout.addWidget(self.button_close)
        self.verticalLayout.addWidget(self.frame_header)
        self.frame_contains = QtWidgets.QFrame(self.frame_main)
        self.frame_contains.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.frame_contains.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_contains.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_contains.setObjectName("frame_contains")
        self.button_cancel = QtWidgets.QPushButton(self.frame_contains)
        self.button_cancel.setGeometry(QtCore.QRect(300, 600, 200, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.button_cancel.setFont(font)
        self.button_cancel.setStyleSheet("QPushButton {\n"
                                         "    border: 2px solid rgb(52, 59, 72);\n"
                                         "    border-radius: 10px;    \n"
                                         "    background-color: rgb(52, 59, 72);\n"
                                         "    color: rgb(255, 255, 255);\n"
                                         "}\n"
                                         "QPushButton:hover {\n"
                                         "    background-color: rgb(57, 65, 80);\n"
                                         "    color: rgb(227, 227, 227);\n"
                                         "    border: 2px solid rgb(61, 70, 86);\n"
                                         "}\n"
                                         "QPushButton:pressed {    \n"
                                         "    background-color: rgb(35, 40, 49);\n"
                                         "    color: rgb(255, 255, 255);\n"
                                         "    border: 2px solid rgb(43, 50, 61);\n"
                                         "}")
        self.button_cancel.setIconSize(QtCore.QSize(40, 40))
        self.button_cancel.setObjectName("button_cancel")
        self.button_accept = QtWidgets.QPushButton(self.frame_contains)
        self.button_accept.setGeometry(QtCore.QRect(70, 600, 200, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.button_accept.setFont(font)
        self.button_accept.setStyleSheet("QPushButton {\n"
                                         "    border: 2px solid rgb(52, 59, 72);\n"
                                         "    border-radius: 10px;    \n"
                                         "    background-color: rgb(52, 59, 72);\n"
                                         "    color: rgb(255, 255, 255);\n"
                                         "}\n"
                                         "QPushButton:hover {\n"
                                         "    background-color: rgb(57, 65, 80);\n"
                                         "    color: rgb(227, 227, 227);\n"
                                         "    border: 2px solid rgb(61, 70, 86);\n"
                                         "}\n"
                                         "QPushButton:pressed {    \n"
                                         "    background-color: rgb(35, 40, 49);\n"
                                         "    color: rgb(255, 255, 255);\n"
                                         "    border: 2px solid rgb(43, 50, 61);\n"
                                         "}")
        self.button_accept.setIconSize(QtCore.QSize(40, 40))
        self.button_accept.setObjectName("button_accept")
        self.table_profiles = QtWidgets.QTableWidget(self.frame_contains)
        self.table_profiles.setGeometry(QtCore.QRect(10, 59, 570, 531))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 44, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 44, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 44, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 44, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 44, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 44, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 44, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 44, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 44, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.table_profiles.setPalette(palette)
        self.table_profiles.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.table_profiles.setStyleSheet("QTableWidget {    \n"
                                          "    background-color: rgb(39, 44, 54);\n"
                                          "    padding: 10px;\n"
                                          "    border-radius: 5px;\n"
                                          "    gridline-color: rgb(44, 49, 60);\n"
                                          "    border-bottom: 1px solid rgb(44, 49, 60);\n"
                                          "}\n"
                                          "QTableWidget::item{\n"
                                          "    border-color: rgb(44, 49, 60);\n"
                                          "    padding-left: 5px;\n"
                                          "    padding-right: 5px;\n"
                                          "    gridline-color: rgb(44, 49, 60);\n"
                                          "}\n"
                                          "QTableWidget::item:selected{\n"
                                          "    background-color: rgb(85, 170, 255);\n"
                                          "}\n"
                                          "QScrollBar:horizontal {\n"
                                          "    border: none;\n"
                                          "    background: rgb(52, 59, 72);\n"
                                          "    height: 14px;\n"
                                          "    margin: 0px 21px 0 21px;\n"
                                          "    border-radius: 0px;\n"
                                          "}\n"
                                          " QScrollBar:vertical {\n"
                                          "    border: none;\n"
                                          "    background: rgb(52, 59, 72);\n"
                                          "    width: 14px;\n"
                                          "    margin: 21px 0 21px 0;\n"
                                          "    border-radius: 0px;\n"
                                          " }\n"
                                          "QHeaderView::section{\n"
                                          "    Background-color: rgb(39, 44, 54);\n"
                                          "    max-width: 30px;\n"
                                          "    border: 1px solid rgb(44, 49, 60);\n"
                                          "    border-style: none;\n"
                                          "    border-bottom: 1px solid rgb(44, 49, 60);\n"
                                          "    border-right: 1px solid rgb(44, 49, 60);\n"
                                          "}\n"
                                          "QTableWidget::horizontalHeader {    \n"
                                          "    background-color: rgb(81, 255, 0);\n"
                                          "}\n"
                                          "QHeaderView::section:horizontal\n"
                                          "{\n"
                                          "    border: 1px solid rgb(32, 34, 42);\n"
                                          "    background-color: rgb(27, 29, 35);\n"
                                          "    color: rgb(255, 255, 255);\n"
                                          "    padding: 3px;\n"
                                          "    border-top-left-radius: 7px;\n"
                                          "    border-top-right-radius: 7px;\n"
                                          "}\n"
                                          "QHeaderView::section:vertical\n"
                                          "{\n"
                                          "    border: 1px solid rgb(44, 49, 60);\n"
                                          "}\n"
                                          "QCheckBox::indicator {\n"
                                          "    border: 3px solid rgb(52, 59, 72);\n"
                                          "    width: 15px;\n"
                                          "    height: 15px;\n"
                                          "    border-radius: 10px;\n"
                                          "    background: rgb(44, 49, 60);\n"
                                          "}\n"
                                          "QCheckBox::indicator:hover {\n"
                                          "    border: 3px solid rgb(58, 66, 81);\n"
                                          "}\n"
                                          "QCheckBox::indicator:checked {\n"
                                          "    background: 3px solid rgb(52, 59, 72);\n"
                                          "    border: 3px solid rgb(52, 59, 72);    \n"
                                          "    background-image: url(:/16x16/data/resources/icons/16x16/cil-check-alt.png);\n"
                                          "}\n"
                                          "")
        self.table_profiles.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.table_profiles.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.table_profiles.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.table_profiles.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_profiles.setAlternatingRowColors(False)
        self.table_profiles.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.table_profiles.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_profiles.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.table_profiles.setRowCount(0)
        self.table_profiles.setColumnCount(5)
        self.table_profiles.setObjectName("table_profiles")
        item = QtWidgets.QTableWidgetItem()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/24x24/data/resources/icons/24x24/cil-uncheck-circle.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        item.setIcon(icon1)
        self.table_profiles.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_profiles.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_profiles.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_profiles.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_profiles.setHorizontalHeaderItem(4, item)
        self.table_profiles.horizontalHeader().setVisible(True)
        self.table_profiles.horizontalHeader().setCascadingSectionResizes(True)
        self.table_profiles.horizontalHeader().setDefaultSectionSize(200)
        self.table_profiles.horizontalHeader().setStretchLastSection(False)
        self.table_profiles.verticalHeader().setVisible(False)
        self.table_profiles.verticalHeader().setHighlightSections(False)
        self.table_profiles.verticalHeader().setStretchLastSection(True)
        self.button_delete = QtWidgets.QPushButton(self.frame_contains)
        self.button_delete.setGeometry(QtCore.QRect(10, 10, 121, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.button_delete.setFont(font)
        self.button_delete.setStyleSheet("QPushButton {\n"
                                         "    border: 2px solid rgb(52, 59, 72);\n"
                                         "    border-radius: 10px;    \n"
                                         "    background-color: rgb(52, 59, 72);\n"
                                         "    color: rgb(255, 255, 255);\n"
                                         "}\n"
                                         "QPushButton:hover {\n"
                                         "    background-color: rgb(57, 65, 80);\n"
                                         "    color: rgb(227, 227, 227);\n"
                                         "    border: 2px solid rgb(61, 70, 86);\n"
                                         "}\n"
                                         "QPushButton:pressed {    \n"
                                         "    background-color: rgb(35, 40, 49);\n"
                                         "    color: rgb(255, 255, 255);\n"
                                         "    border: 2px solid rgb(43, 50, 61);\n"
                                         "}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/16x16/data/resources/icons/16x16/cil-remove.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.button_delete.setIcon(icon2)
        self.button_delete.setIconSize(QtCore.QSize(40, 40))
        self.button_delete.setObjectName("button_delete")
        self.verticalLayout.addWidget(self.frame_contains)

        self.retranslateUi(FormDeviceDatabaseView)
        QtCore.QMetaObject.connectSlotsByName(FormDeviceDatabaseView)

    def retranslateUi(self, FormDeviceDatabaseView):
        _translate = QtCore.QCoreApplication.translate
        FormDeviceDatabaseView.setWindowTitle(_translate("FormDeviceDatabaseView", "Device Database View"))
        self.label_title.setText(_translate("FormDeviceDatabaseView", "View of Device"))
        self.button_close.setToolTip(_translate("FormDeviceDatabaseView", "Close"))
        self.button_cancel.setText(_translate("FormDeviceDatabaseView", "Cancel"))
        self.button_accept.setText(_translate("FormDeviceDatabaseView", "Accept"))
        self.table_profiles.setSortingEnabled(False)
        item = self.table_profiles.horizontalHeaderItem(1)
        item.setText(_translate("FormDeviceDatabaseView", "ID"))
        item = self.table_profiles.horizontalHeaderItem(2)
        item.setText(_translate("FormDeviceDatabaseView", "Image"))
        item = self.table_profiles.horizontalHeaderItem(3)
        item.setText(_translate("FormDeviceDatabaseView", "Name"))
        item = self.table_profiles.horizontalHeaderItem(4)
        item.setText(_translate("FormDeviceDatabaseView", "Department"))
        self.button_delete.setText(_translate("FormDeviceDatabaseView", "Delete"))


import files_rc

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    FormDeviceDatabaseView = QtWidgets.QWidget()
    ui = Ui_FormDeviceDatabaseView()
    ui.setupUi(FormDeviceDatabaseView)
    FormDeviceDatabaseView.show()
    sys.exit(app.exec_())
